version: '3.8'

services:
  scprep:
    build: .
    image: scprep:latest
    container_name: scprep-container
    volumes:
      - ./data:/scprep/data
      - ./output:/scprep/output
    environment:
      - DISABLE_AUTH=true
    ports:
      - "8787:8787"
    command: R
    
  scprep-rstudio:
    image: rocker/rstudio:4.2.1
    container_name: scprep-rstudio
    volumes:
      - .:/home/rstudio/scprep
      - ./data:/home/rstudio/data
      - ./output:/home/rstudio/output
    environment:
      - DISABLE_AUTH=true
    ports:
      - "8788:8787"